modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ShakterNano/Entranced/issues"
license = "MIT"

[[mods]]
    modId = "entranced"
    version = "${version}"
    displayName = "Entranced"
    displayURL = "https://github.com/ShakterNano/Entranced"
    authors = "ShaksterNano"
    description = '''
        An enchantment mod
    '''
    logoFile = "icon.png"

[[dependencies.entranced]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.entranced]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.entranced]]
    modId = "architectury"
    mandatory = true
    versionRange = "[4.0.27,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.entranced]]
    modId = "cloth_config"
    mandatory = true
    versionRange = "[6.2.57,)"
    ordering = "AFTER"
    side = "BOTH"
